/**
 * Slugs are generated by the system from human names/titles and never edited
 * after creation. Use slugify() for the base, then ensureUniqueSlug() to pick
 * a free variant within the relevant scope (typically per-creator).
 */

const MIN_LENGTH = 2;
const MAX_LENGTH = 60;
const FALLBACK = "item";

export function slugify(input: string, maxLength: number = MAX_LENGTH): string {
  const base = input
    .normalize("NFKD")
    .replace(/\p{M}+/gu, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, maxLength);

  if (base.length >= MIN_LENGTH) return base;
  return FALLBACK;
}

export async function ensureUniqueSlug(
  base: string,
  isTaken: (candidate: string) => Promise<boolean>,
  maxLength: number = MAX_LENGTH,
): Promise<string> {
  if (!(await isTaken(base))) return base;
  for (let i = 2; i < 10_000; i++) {
    const suffix = `-${i}`;
    const candidate = `${base.slice(0, maxLength - suffix.length)}${suffix}`.replace(
      /^-+|-+$/g,
      "",
    );
    if (!(await isTaken(candidate))) return candidate;
  }
  throw new Error("Unable to find a unique slug");
}
